Resources:
  UserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      ClientName: ${self:service}-${self:provider.stage}-client
      GenerateSecret: false
      UserPoolId:
        Ref: UserPool