Resources:
  UserPoolAdminUserToAdminGroup:
    Type: "AWS::Cognito::UserPoolUserToGroupAttachment"
    DependsOn: UserPoolAdminUser
    Properties:
      GroupName: Admin
      Username: admin
      UserPoolId:
        Ref: UserPool