Resources:
  S3HostingBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: ${self:custom.s3HostingBucket}
      AccessControl: "PublicRead"
      WebsiteConfiguration:
        IndexDocument: "index.html"

  S3HostingBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket:
        Ref: S3HostingBucket
      PolicyDocument:
        Statement:
        - Sid: PublicReadGetObject
          Effect: Allow
          Principal: "*"
          Action:
          - s3:GetObject
          Resource: arn:aws:s3:::${self:custom.s3HostingBucket}/*